export default[
    {
        id: 1,
        postedOn : '2024-06-21',
        title: 'iOS Developer',
        company: 'Apple' ,
        type: 'Full Time',
        experience: 'Intermediate',
        location: 'Remote',
        skills: ["SwiftUI", "UiKit", "Core Data"],
        job_link:"https://www.apple.com/careers/in/",
    },
    {
        id: 2,
        postedOn: '2024-06-18',
        title: 'Frontend Developer',
        type:"Full Time",
        location: "In-office",
        experience: "Fresher",
        company: "Amazon",
        skills: ["Javascript","Nextjs", "Tailwind CSS"],
        job_link: "https://www.amazon.jobs/en/",
    },
    {
        id: 3,
        postedOn: '2024-06-10',
        title: "Android Developer",
        type: "Part Time",
        location: "Remote",
        experience: "Advanced",
        company: "Facebook",
        skills: ["Kotlin", "MVVM"],
        job_link: "https://www.linkedin.com/company/facebook/jobs/",

    },
    {
        id: 4,
        postedOn: '2024-06-09',
        title: "Backend Developer",
        type: "Contract",
        location: "Hybrid",
        experience: "Beginner",
        company: "Google",
        skills: ["Mongodb", "Nodejs"],
        job_link: "https://www.google.com/about/careers/applications/",

    },
    {
        id: 5,
        postedOn: '2024-06-12',
        title: "Game Developer",
        type: "Full Time",
        location: "In-Office",
        experience: "Intermediate",
        company: "Microsoft",
        skills: ["Game Design", "Graphics Programming"],
        job_link: "https://www.google.com/about/careers/applications/",

    },
    {
        id: 6,
        postedOn: '2024-06-14',
        title: "Developer Advocate",
        type: "Part Time",
        location: "Hybrid",
        experience: "Beginner",
        company: "Amazon Web Services (AWS)",
        skills: ["Node.js", "Django"],
        job_link: "https://aws.amazon.com/careers/",

    }
]